name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-unit:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    env:
      TEST_ENV: review
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: "Install pnpm"
        run: npm install -g pnpm
      - name: "Install dependencies"
        run: pnpm install
      - name: "Run Vitest tests"
        run: npx vitest run --reporter=verbose
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30
